### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by cecton** [big-data-europe/app-http-logger#1]
Hello,

Here are the list of problems I spotted:

 *  The file docker-compose-ETMS.yml file is missing: https://github.com/big-data-europe/mu-bde-logging/blob/master/docker-compose.yml#L41
 *  In the readme: https://github.com/big-data-europe/mu-bde-logging/blob/master/README.md#prerequisites You don't specify it the logging=true is a label or an environment variable. Because of the character case, I assume a label.
 *  The user should not start the application in debug mode by default. https://github.com/big-data-europe/mu-bde-logging/blob/master/docker-compose.yml#L12
 *  mu-docker-event-query also logs queries

As we discussed, sometimes the label is not added to the database. I could not reproduce it at the moment but it could be related to https://github.com/big-data-europe/mu-swarm-logger-service/pull/12 .

**Comment by fr0gs** [comment]
Hello.

I should specify in README that **docker-compose-ETMS.yml** file just represents the docker-compose.yml file of the docker network you wish to log. 
It means that if you wish to log all the events for a given docker-compose project, you need to mount that docker-compose as a volume in the docker-compose.yml of mu-bde-logging.

It is a little bit confusing, that file is not missing, is variable depending on what you want to log. I could add an empty one as default.

**Comment by cecton** [comment]
And what ETMS stands for?

**Comment by madnificent** [comment]
I believe this issue can be closed with the changes that happened to the repository.

- The docker-compose.yml file is not needed anymore thanks to both @fr0gs and @cecton :raised_hands:
- The readme was updated to explicit the use of labels

For other issues, please create a new GitHub ticket or ask me to add it to our TP instance.
